Rename to gitlab-logs

diff --git a/bin/gitlab-logs b/bin/gitlab-logs
--- a/bin/gitlab-logs
+++ b/bin/gitlab-logs
@@ -1,39 +1,37 @@
 #!/bin/bash
 
-# Check if the first argument (initial job id) is provided
 if [ -z "$1" ]; then
-    echo "Usage: gitlab-logs <initial_job_id> [<number_of_jobs>]"
+    echo "Usage: gitlab-jobs <pipeline-id> [<name-filter>]"
     exit 1
 fi
 
-# Test if glab is installed
 if ! command -v glab &>/dev/null; then
     echo "Error: glab is not installed. Please install glab to use this script."
     exit 1
 fi
 
-# Assign arguments to variables
-initial_job_id=$1
-num_jobs=${2:-1} # Default to 1 if no second argument is provided
+if ! command -v jq &>/dev/null; then
+    echo "Error: jq is not installed. Please install glab to use this script."
+    exit 1
+fi
+
+pipeline_id=$1
+filter=${2:-}
+
+jq_expr='.jobs | map(select(.name | contains("'$filter'"))) | map(.id) | .[]'
+job_ids=$(glab ci get -p "$pipeline_id" -F json | jq -r "$jq_expr")
 
 # Create the output file path
-output_file="/tmp/gitlab-jobs-${initial_job_id}-${num_jobs}.txt"
-
-# Inform the user
-echo "Fetching logs for jobs starting from ${initial_job_id} for ${num_jobs} jobs"
-echo "Output will be saved to ${output_file}"
+output_file="/tmp/gitlab-jobs-${pipeline_id}-${filter}.txt"
 
 # Initialize or clear the output file
 >"$output_file"
 
-# Fetch logs for each job ID and append to the output file
-for ((i = 0; i < num_jobs; i++)); do
-    job_id=$((initial_job_id + i))
+for job_id in $job_ids; do
     echo "Fetching logs for job ID: $job_id"
     echo "===== Logs for Job ID: $job_id =====" >>"$output_file"
     glab ci trace "$job_id" >>"$output_file" 2>&1
     echo "===== End of Logs for Job ID: $job_id =====" >>"$output_file"
 done
 
-# Inform the user that the operation is complete
 echo "Logs have been fetched and saved to ${output_file}"
