Xmonad: password command working with lpass or keypass

diff --git a/bin/lastpass-rofi b/bin/lastpass-rofi
--- a/bin/lastpass-rofi
+++ b/bin/lastpass-rofi
@@ -7,28 +7,28 @@
 # Check for required tools
 REQUIRED_COMMANDS="rofi lpass zenity"
 for COMMAND in $REQUIRED_COMMANDS; do
-    if ! [ -x "$(command -v "$COMMAND")" ]; then
-        zenity --error --text="Command '$COMMAND' not found"
-        exit 1
-    fi
+	if ! [ -x "$(command -v "$COMMAND")" ]; then
+		echo "Command '$COMMAND' not found"
+		exit 1
+	fi
 done
 
 # Login
 if ! lpass status; then
-    # environment variable `LPASS_USER` is read
-    [ -z "$LPASS_USER" ] && LPASS_USER="$(zenity --entry --text='LastPass Username:')"
-    [ -z "$LPASS_USER" ] && exit
+	# environment variable `LPASS_USER` is read
+	[ -z "$LPASS_USER" ] && LPASS_USER="$(zenity --entry --text='LastPass Username:')"
+	[ -z "$LPASS_USER" ] && exit
 
-    if ! lpass login --trust "$LPASS_USER"; then
-        zenity --error --text="Failed to login to LastPass. Please check your credentials and try again."
-        exit 1
-    fi
+	if ! lpass login --trust "$LPASS_USER"; then
+		zenity --error --text="Failed to login to LastPass. Please check your credentials and try again."
+		exit 1
+	fi
 fi
 
 # Selection
 ROFI_SELECTION="$(lpass ls --format '•%an' | grep '•' | tr '•' '\n' | sed '/^$/d' | rofi -dmenu -i -p LastPass)"
 if [ -z "${ROFI_SELECTION}" ]; then
-    exit
+	exit
 fi
 
 # Copy to clipboard
